# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaee762acfdd0d892fa0f57f58763ba3418d95b6dce717a4bc45c8127ea2391a25172e124c9337a813cdf1222cc249e00ffeb4453d0ff3e8bb42d0b0534a73e5

test:
  secret_key_base: 7b8981b84e8a830f25ee382530077906a8fb94a922d27462c633776ca808821a07c407546de9be4559e1361847ab32214b11bb6de23ab4f091acd892f2d9a935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
